# Generated by Django 4.1.2 on 2022-10-16 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendar',
            name='file',
        ),
        migrations.AddField(
            model_name='calendar',
            name='url',
            field=models.URLField(default=None),
        ),
        migrations.AlterField(
            model_name='room',
            name='id',
            field=models.CharField(default='BYCCO', max_length=5, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
