# Generated by Django 4.1.2 on 2022-10-16 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_calendar_id_alter_room_id_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='id',
            field=models.CharField(default='TRJ3N', max_length=5, primary_key=True, serialize=False),
        ),
    ]
