# Generated by Django 4.1.2 on 2022-10-16 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_room_id_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='id',
            field=models.CharField(default='9MKZU', max_length=5, primary_key=True, serialize=False),
        ),
    ]
